[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kovisoft/slimv'

[[plugins]] # クリップボード貼り付けによるインデント崩れを抑える
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]] # JavaScript
repo = 'ternjs/tern_for_vim'
build = 'npm install'

[[plugins]] # カーソル位置によってftを自動切り替え
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のftを判定
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'sainnhe/sonokai'
hook_add = '''
  let g:sonokai_disable_italic_comment = 1
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  au MyAutoCmd VimEnter * nested colorscheme sonokai
'''

[[plugins]] # インデントの色
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # ステータスラインの色
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'wombat'
    \}
'''
