[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]] # jsの補完
repo = 'mattn/jscomplete-vim'
on_ft = ['javascript']

[[plugins]] # Node.jsの補完
repo = 'myhere/vim-nodejs-complete'
on_ft = ['javascript']
